# Generated by Django 4.1.4 on 2023-01-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.TextField()),
                ("title", models.TextField()),
                ("image", models.TextField()),
                ("description", models.TextField()),
                ("content", models.TextField()),
            ],
        ),
    ]
