# Generated by Django 4.1.4 on 2023-01-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="url",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
